const { Client } = require('pg');
const fs = require('fs');
require('dotenv').config();

const schemaSql = `
-- 1. HABILITAR EXTENSÕES ESSENCIAIS
create extension if not exists vector;       -- Para IA e Embeddings
create extension if not exists pgcrypto;     -- Para criptografia e UUIDs
create extension if not exists pg_trgm;      -- Para busca textual rápida (fuzzy search)

-- 2. PERFIS DE USUÁRIO (Sincronizado com Auth)
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  username text unique not null,
  display_name text,
  photo_url text,
  bio text,
  city text,
  state text,
  phone_number text,
  cpf text,
  instagram text,
  facebook text,
  slogan text,
  is_profile_public boolean default true,
  credits int default 0,
  lifetime_xp int default 0,
  badges text[] default '{}',
  subscription_tier text default 'free', -- free, bronze, silver, gold, pastor
  subscription_status text default 'active',
  subscription_expires_at timestamptz,
  theme text default 'light',
  activity_log jsonb default '[]',
  stats jsonb default '{}',
  last_reading_position jsonb default '{}',
  usage_today jsonb default '{}',
  reading_plan jsonb default '{}',
  progress jsonb default '{}',
  enrolled_plans text[] default '{}',
  church_data jsonb default '{}',
  followers_count int default 0,
  following_count int default 0,
  created_at timestamptz default now()
);

-- 3. BÍBLIA SAGRADA (O Coração do App)
create table if not exists public.bible_books (
  id text primary key, -- ex: 'gn', 'jo'
  name text not null,
  testament text not null -- 'old', 'new'
);

create table if not exists public.bible_verses (
  id bigint generated by default as identity primary key,
  book_id text references public.bible_books(id),
  chapter int not null,
  verse int not null,
  text text not null,
  embedding vector(1536) 
);

create index if not exists bible_verses_book_chapter_verse_idx on public.bible_verses (book_id, chapter, verse);

-- 4. CONTEÚDO GERADO PELO USUÁRIO (UGC)

-- Estudos Privados (Drafts)
create table if not exists public.studies (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) not null,
  title text not null,
  description text,
  content text,
  source_text text,
  analysis text,
  source text default 'geral',
  category text,
  status text default 'draft',
  blocks text default '[]',
  meta text default '{}',
  cover_image text,
  is_public boolean default false,
  tags text[] default '{}',
  metrics jsonb default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Estudos Públicos (Vitrine)
create table if not exists public.public_studies (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) not null,
  user_name text,
  user_photo text,
  title text not null,
  description text,
  content text,
  source_text text,
  analysis text,
  source text default 'geral',
  category text,
  type text default 'article',
  slug text,
  blocks text default '[]',
  meta text default '{}',
  cover_image text,
  status text default 'draft',
  tags text[] default '{}',
  views_count int default 0,
  shares_count int default 0,
  likes_count int default 0,
  published_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Anotações Pessoais
create table if not exists public.notes (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) not null,
  book_id text references public.bible_books(id),
  chapter int,
  verse int,
  content text not null,
  is_public boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 5. SOCIAL & COMUNIDADE

create table if not exists public.churches (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  slug text unique not null,
  acronym text,
  denomination text,
  location_city text,
  location_state text,
  location_address text,
  logo_url text,
  pastor_name text,
  created_at timestamptz default now()
);

create table if not exists public.cells (
  id uuid default gen_random_uuid() primary key,
  church_id uuid references public.churches(id),
  parent_group_id uuid references public.cells(id),
  name text not null,
  slug text unique not null,
  leader_id uuid references public.profiles(id),
  leader_name text,
  created_by uuid references public.profiles(id),
  created_at timestamptz default now()
);

create table if not exists public.memberships (
  user_id uuid references public.profiles(id) primary key,
  church_id uuid references public.churches(id),
  cell_id uuid references public.cells(id),
  role text default 'member', 
  joined_at timestamptz default now()
);

create table if not exists public.follows (
  id uuid default gen_random_uuid() primary key,
  follower_id uuid references public.profiles(id) not null,
  following_id uuid references public.profiles(id) not null,
  created_at timestamptz default now(),
  unique(follower_id, following_id)
);

create table if not exists public.church_followers (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) not null,
  church_id uuid references public.churches(id) not null,
  followed_at timestamptz default now(),
  unique(user_id, church_id)
);

create table if not exists public.posts (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) not null,
  user_display_name text,
  user_username text,
  user_photo_url text,
  content text,
  image_url text,
  type text default 'reflection',
  destination text default 'global',
  likes_count int default 0,
  comments_count int default 0,
  shares_count int default 0,
  liked_by jsonb default '[]',
  church_id uuid references public.churches(id),
  cell_id uuid references public.cells(id),
  created_at timestamptz default now()
);

create table if not exists public.prayer_requests (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) not null,
  user_name text,
  user_photo_url text,
  content text not null,
  target_type text, -- 'global', 'church', 'cell'
  target_id uuid,   
  church_id uuid references public.churches(id),
  cell_name text,
  intercessors_count int default 0,
  intercessors jsonb default '[]',
  created_at timestamptz default now()
);

-- 6. JORNADAS & LMS

create table if not exists public.custom_plans (
  id uuid default gen_random_uuid() primary key,
  author_id uuid references public.profiles(id) not null,
  author_name text,
  title text not null,
  description text,
  category text,
  cover_url text,
  weeks jsonb default '[]',
  is_public boolean default false,
  privacy_type text default 'public',
  is_ranked boolean default false,
  status text default 'draft',
  church_id uuid references public.churches(id),
  group_id uuid references public.cells(id),
  subscribers_count int default 0,
  planning_frequency text default 'weekly',
  has_evaluation boolean default false,
  evaluation_id uuid,
  teams jsonb default '[]',
  team_scores jsonb default '{}',
  start_date timestamptz,
  end_date timestamptz,
  metrics jsonb default '{}',
  tags text[] default '{}',
  views_count int default 0,
  shares_count int default 0,
  completions_count int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.plan_participants (
  id uuid default gen_random_uuid() primary key,
  plan_id uuid references public.custom_plans(id) on delete cascade,
  uid uuid references public.profiles(id) not null,
  display_name text,
  username text,
  photo_url text,
  points int default 0,
  completed_steps jsonb default '[]',
  team text,
  status text default 'active',
  joined_at timestamptz default now(),
  last_activity_at timestamptz default now(),
  invited_by uuid references public.profiles(id),
  unique(plan_id, uid)
);

create table if not exists public.guided_prayers (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  content text not null,
  category text,
  author_id uuid references public.profiles(id),
  author_name text,
  church_id uuid references public.churches(id),
  audio_url text,
  is_template boolean default false,
  generated_by text default 'pastor',
  created_at timestamptz default now()
);

create table if not exists public.reading_tracks (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  description text,
  author_id uuid references public.profiles(id),
  generated_by text default 'pastor',
  scope text default 'personal',
  tags jsonb default '[]',
  steps jsonb default '[]',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.evaluations (
  id uuid default gen_random_uuid() primary key,
  plan_id uuid references public.custom_plans(id),
  author_id uuid references public.profiles(id),
  title text not null,
  description text,
  time_limit_minutes int default 0,
  passing_score int default 70,
  questions jsonb default '[]',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 7. SISTEMA & CONFIGURAÇÃO

create table if not exists public.settings (
  key text primary key,
  value jsonb not null
);

create table if not exists public.notifications (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) not null,
  title text not null,
  message text not null,
  type text default 'info',
  link text,
  read boolean default false,
  timestamp timestamptz default now()
);

create table if not exists public.banners (
  id uuid default gen_random_uuid() primary key,
  title text,
  subtitle text,
  image_url text,
  link text,
  active boolean default true,
  priority int default 0,
  type text default 'hero',
  created_at timestamptz default now()
);

create table if not exists public.daily_devotionals (
  date text primary key, -- YYYY-MM-DD
  title text,
  verse_reference text,
  verse_text text,
  content text,
  prayer text,
  created_at timestamptz default now()
);

create table if not exists public.user_teams (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) not null,
  name text not null,
  color text,
  members jsonb default '[]',
  created_at timestamptz default now()
);

create table if not exists public.support_tickets (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id),
  user_email text,
  user_name text,
  subject text,
  message text,
  status text default 'open',
  created_at timestamptz default now()
);

create table if not exists public.report_tickets (
  id uuid default gen_random_uuid() primary key,
  type text, -- post, comment, user, bug
  target_id uuid,
  reporter_id uuid references public.profiles(id),
  reason text,
  severity text,
  status text default 'pending',
  created_at timestamptz default now()
);

-- 8. FUNÇÃO RPC PARA BUSCA SEMÂNTICA (RAG)
create or replace function match_verses (
  query_embedding vector(1536),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  book_id text,
  chapter int,
  verse int,
  text text,
  similarity float
)
language sql stable
as $$
  select
    v.id,
    v.book_id,
    v.chapter,
    v.verse,
    v.text,
    1 - (v.embedding <=> query_embedding) as similarity
  from public.bible_verses v
  where 1 - (v.embedding <=> query_embedding) > match_threshold
  order by v.embedding <=> query_embedding
  limit match_count;
-- 9. POLÍTICAS DE SEGURANÇA (RLS)

-- Habilitar RLS em tudo
alter table public.profiles enable row level security;
alter table public.studies enable row level security;
alter table public.public_studies enable row level security;
alter table public.notes enable row level security;
alter table public.posts enable row level security;
alter table public.prayer_requests enable row level security;
alter table public.notifications enable row level security;
alter table public.custom_plans enable row level security;
alter table public.plan_participants enable row level security;

-- Perfis: Qualquer um vê, dono edita
create policy "Perfis são públicos" on public.profiles for select using (true);
create policy "Usuários editam próprio perfil" on public.profiles for update using (auth.uid() = id);
create policy "Usuários inserem próprio perfil" on public.profiles for insert with check (auth.uid() = id);

-- Estudos: Dono vê/edita
create policy "Usuários veem próprios estudos" on public.studies for select using (auth.uid() = user_id);
create policy "Usuários editam próprios estudos" on public.studies for all using (auth.uid() = user_id);

-- Estudos Públicos: Qualquer um vê
create policy "Estudos públicos são visíveis" on public.public_studies for select using (true);
create policy "Usuários postam estudos públicos" on public.public_studies for insert with check (auth.uid() = user_id);
create policy "Usuários editam próprios estudos públicos" on public.public_studies for update using (auth.uid() = user_id);
create policy "Usuários deletam próprios estudos públicos" on public.public_studies for delete using (auth.uid() = user_id);

-- Posts: Qualquer um vê, dono edita
create policy "Posts são públicos" on public.posts for select using (true);
create policy "Usuários criam posts" on public.posts for insert with check (auth.uid() = user_id);
create policy "Usuários editam próprios posts" on public.posts for update using (auth.uid() = user_id);

-- Notificações: Privado
create policy "Usuários veem próprias notificações" on public.notifications for select using (auth.uid() = user_id);
create policy "Usuários editam próprias notificações" on public.notifications for update using (auth.uid() = user_id);

-- Planos Customizados
create policy "Planos públicos são visíveis" on public.custom_plans for select using (is_public = true or auth.uid() = author_id);
create policy "Autores gerenciam planos" on public.custom_plans for all using (auth.uid() = author_id);

-- Participantes de Planos
create policy "Membros veem participantes" on public.plan_participants for select using (true);
create policy "Usuários se inscrevem em planos" on public.plan_participants for insert with check (auth.uid() = uid);
create policy "Usuários atualizam próprio progresso" on public.plan_participants for update using (auth.uid() = uid);
`;

async function applySchema() {
  const client = new Client({
    user: 'postgres',
    host: 'aws-0-sa-east-1.pooler.supabase.com',
    database: 'postgres',
    password: '[$3curityAmr550903]',
    port: 6543,
    ssl: {
      rejectUnauthorized: false
    }
  });

  try {
    await client.connect();
    console.log('Connected to PostgreSQL database.');
    await client.query(schemaSql);
    console.log('Schema applied successfully.');
  } catch (err) {
    console.error('Error applying schema:', err.message);
  } finally {
    await client.end();
  }
}

applySchema();
